name: CI
on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: [8.1, 8.2, 8.3, 8.4]
        laravel: ["^10.0", "^11.0", "^12.0"]
        dependency-version: [prefer-lowest, prefer-stable]
        include:
          # Laravel 12
          - php: 8.4
            laravel: "^12.0"
          - php: 8.3
            laravel: "^12.0"
          - php: 8.2
            laravel: "^12.0"

          # Laravel 11
          - php: 8.4
            laravel: "^11.0"
          - php: 8.3
            laravel: "^11.0"
          - php: 8.2
            laravel: "^11.0"

          # Laravel 10
          - php: 8.3
            laravel: "^10.0"
          - php: 8.2
            laravel: "^10.0"
          - php: 8.1
            laravel: "^10.0"
        exclude:
          - php: 8.1
            laravel: "^11.0"
          - php: 8.1
            laravel: "^12.0"

    name: PHP ${{ matrix.php }} - Laravel ${{ matrix.laravel }} - Dependency Version ${{ matrix.dependency-version }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, pdo_mysql, zip, bcmath, curl, json, fileinfo
          coverage: none

      - name: Install Dependencies
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" --no-update --no-interaction
          composer update --${{ matrix.dependency-version }} --no-interaction --prefer-dist

      - name: Run Tests
        run: |
          vendor/bin/pest --parallel
